services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password

    volumes:
      - wordpress_data:/var/www/html
    networks:
      - app-network

  db:
    container_name: database
    image: mysql:5.7
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password  # Update this to your new password

    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  node-server:
    container_name: node-server
    build:
      context: ./node-server
    ports:
      - "3000:3000"
    depends_on:
      - python-service
      - wordpress
    networks:
      - app-network

  python-service:
    container_name: python-service
    build:
      context: ./python-service
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  wordpress_data:
  db_data:
