version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password  # Update this to your new password
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password  # Update this to your new password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password  # Update this to your new password
    volumes:
      - db_data:/var/lib/mysql

  nodejs-backend:
    build:
      context: ./wordpress-node-backend
    container_name: nodejs-backend
    ports:
      - "3000:3000"
    depends_on:
      - python-service

  python-service:
    build:
      context: ./wordpress-python-service
    container_name: python-service
    ports:
      - "5000:5000"

volumes:
  db_data:
